//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_MASTER_TX
    {
        public decimal FINANSYS_TRANSACTION_SKEY { get; set; }
        public string FINANCIAL_ORG_CODE { get; set; }
        public string CUSTOMER_PLANT_DUNS { get; set; }
        public string BILL_TO_RECORD_KEY { get; set; }
        public string SHIP_TO_RECORD_KEY { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string UNITS_CODE { get; set; }
        public string INSIDE_SALES_TEAM_TEXT { get; set; }
        public string SALES_REGION { get; set; }
        public string PAYMENT_TERMS_CODE { get; set; }
        public string HOLD_FOR_CUST_RELEASE_FLAG { get; set; }
        public string INVOICE_VIA_EDI_FLAG { get; set; }
        public string INVOICE_VIA_MAIL_FLAG { get; set; }
        public string INVOICE_VIA_EMAIL_FLAG { get; set; }
        public string INVOICE_VIA_FAX_FREQ_CODE { get; set; }
        public string TEST_REPORT_EDI_FLAG { get; set; }
        public string TEST_REPORT_MAIL_FLAG { get; set; }
        public string TEST_REPORT_EMAIL_FLAG { get; set; }
        public string TEST_REPORT_FAX_FREQ_CODE { get; set; }
        public string ORDER_ACK_VIA_EDI_FLAG { get; set; }
        public string ORDER_ACK_VIA_MAIL_FLAG { get; set; }
        public string ORDER_ACK_VIA_EMAIL_FLAG { get; set; }
        public string ORDER_ACK_VIA_FAX_FREQ_CODE { get; set; }
        public string SHIP_NOTICE_VIA_EDI_FLAG { get; set; }
        public string SHIP_NOTICE_VIA_MAIL_FLAG { get; set; }
        public string SHIP_NOTICE_VIA_EMAIL_FLAG { get; set; }
        public string SHIP_NOTICE_VIA_FAX_FREQ_CODE { get; set; }
        public string SIC_CODE { get; set; }
        public string FEDERAL_TAX_ID { get; set; }
        public string TAX_EXEMPT_CERTIFICATE { get; set; }
        public string CUSTOMER_NOTE_1 { get; set; }
        public string CUSTOMER_NOTE_2 { get; set; }
        public string CREDIT_STATUS_CODE { get; set; }
        public string SHIP_MODE_CODE { get; set; }
        public string FREIGHT_PAYMENT { get; set; }
        public string PREFERRED_CARRIER { get; set; }
        public string FREIGHT_CONTRACT { get; set; }
        public string DELIVERY_ROUTE { get; set; }
        public string RECEIVING_HOURS { get; set; }
        public string SHIPPING_NOTE_1 { get; set; }
        public string SHIPPING_NOTE_2 { get; set; }
        public string SHIPPING_NOTE_3 { get; set; }
        public string SHIPPING_NOTE_4 { get; set; }
        public string ACCOUNT_TYPE_CODE { get; set; }
        public string OUTSIDE_SALES_TEAM_TEXT { get; set; }
        public string SHIPTO_DUNS { get; set; }
        public string HOLD_INVOICE_FLAG { get; set; }
    }
}
