//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyStore
    {
        public int KeyStoreID { get; set; }
        public decimal LastTrackSysProcessed { get; set; }
        public Nullable<System.DateTimeOffset> LastTrackSysProcessedTime { get; set; }
        public decimal LastFinanSysUsed { get; set; }
        public Nullable<System.DateTimeOffset> LastFinanSysUsedTime { get; set; }
        public string LastTrackSysDescription { get; set; }
        public string LastFinanSysDescription { get; set; }
    }
}
