//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenTracModel : DbContext
    {
        public OpenTracModel()
            : base("name=OpenTracModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KeyStore> KeyStores { get; set; }
        public virtual DbSet<PREQ_HEAD_TX> PREQ_HEAD_TX { get; set; }
        public virtual DbSet<PREQ_LINE_TX> PREQ_LINE_TX { get; set; }
        public virtual DbSet<CONTACT_TX> CONTACT_TX { get; set; }
        public virtual DbSet<CUSTOMER_MASTER_TX> CUSTOMER_MASTER_TX { get; set; }
        public virtual DbSet<MILL_TRANS_IN_TX> MILL_TRANS_IN_TX { get; set; }
        public virtual DbSet<TRANSACTION_INBOUND> TRANSACTION_INBOUND { get; set; }
        public virtual DbSet<TRANSACTION_OUTBOUND> TRANSACTION_OUTBOUND { get; set; }
    }
}
