//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREQ_LINE_TX
    {
        public decimal TRACKSYS_TRANSACTION_SKEY { get; set; }
        public decimal LINE_NUMBER { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string PRICE_UMCODE { get; set; }
        public Nullable<decimal> PROCESSING_CHARGE { get; set; }
        public Nullable<decimal> STORAGE_IN_CHARGE { get; set; }
        public Nullable<decimal> STORAGE_OUT_CHARGE { get; set; }
        public Nullable<decimal> STORAGE_DAY_CHARGE { get; set; }
        public Nullable<decimal> STORAGE_FREE_DAYS { get; set; }
        public Nullable<decimal> MISC_CHARGE { get; set; }
        public Nullable<decimal> STORAGE_EXPECTED_DAYS { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> EXTENDED_COST { get; set; }
        public string SPECIAL_INSTR_LINE_1 { get; set; }
        public string SPECIAL_INSTR_LINE_2 { get; set; }
        public string SPECIAL_INSTR_LINE_3 { get; set; }
        public Nullable<decimal> TRACKSYS_PART_NUMBER { get; set; }
        public Nullable<decimal> TRACKSYS_PART_REVISION { get; set; }
        public string FINANSYS_BILLTO_KEY { get; set; }
        public string FINANSYS_SHIPTO_KEY { get; set; }
        public string GL_ACCOUNT_NUMBER { get; set; }
        public Nullable<decimal> MATERIAL_CHARGE { get; set; }
        public Nullable<decimal> FREIGHT1_CHARGE { get; set; }
        public Nullable<decimal> FREIGHT2_CHARGE { get; set; }
    }
}
