//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREQ_HEAD_TX
    {
        public decimal TRACKSYS_TRANSACTION_SKEY { get; set; }
        public string FINANCIAL_ORG_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> ORDER_RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> TRACKSYS_PREQ_NUMBER { get; set; }
        public Nullable<decimal> TRACKSYS_PREQ_REV_NUM { get; set; }
        public string FINANSYS_VENDOR_KEY { get; set; }
        public string PREQ_CREATED_BY { get; set; }
    }
}
