//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoilStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoilReading
    {
        public long CoilReadingId { get; set; }
        public long CoilId { get; set; }
        public int ReadingNumber { get; set; }
        public decimal Value { get; set; }
    
        public virtual Coil Coil { get; set; }
    }
}
