//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoilStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coil
    {
        public Coil()
        {
            this.CoilReadings = new HashSet<CoilReading>();
        }
    
        public long CoilId { get; set; }
        public string CoilNumber { get; set; }
        public Nullable<System.DateTimeOffset> ProducedTime { get; set; }
        public Nullable<int> GageInUse { get; set; }
        public Nullable<int> NumberOfReadings { get; set; }
        public Nullable<decimal> OrderValue { get; set; }
        public Nullable<decimal> PositiveTolerance { get; set; }
        public Nullable<decimal> NegativeTolerance { get; set; }
        public Nullable<System.DateTime> CreationTimeUTC { get; set; }
        public string Readings { get; set; }
        public string DataType { get; set; }
    
        public virtual ICollection<CoilReading> CoilReadings { get; set; }
    }
}
