//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_TX
    {
        public decimal FINANSYS_TRANSACTION_SKEY { get; set; }
        public string SERVICE_CODE { get; set; }
        public string CONTACT_RECORD_KEY { get; set; }
        public string ACTION_CODE { get; set; }
        public string FORMAT_CODE { get; set; }
        public string NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string ADDR_LINE_1 { get; set; }
        public string ADDR_LINE_2 { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_TEXT { get; set; }
        public string CITY_TEXT { get; set; }
        public string REGION_CODE { get; set; }
        public string REGION_TEXT { get; set; }
        public string POSTAL_CODE { get; set; }
        public string URL { get; set; }
    }
}
