//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class MILL_TRANS_IN_TX
    {
        public decimal FINANSYS_TRANSACTION_SKEY { get; set; }
        public string FINANCIAL_ORG_CODE { get; set; }
        public string SENDER_QUAL { get; set; }
        public string SENDER_ID { get; set; }
        public string RECEIVER_QUAL { get; set; }
        public string RECEIVER_ID { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string ACKNOWLEDGEMENT_CODE { get; set; }
        public string APPLICATION { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
