//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTracDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_INBOUND
    {
        public decimal TRACKSYS_TRANSACTION_SKEY { get; set; }
        public string ENTITY_TYPE_CODE { get; set; }
        public string TRANSACTION_TYPE_CODE { get; set; }
        public System.DateTime SUBMISSION_DATETIME { get; set; }
        public string ENTITY_CODE { get; set; }
    }
}
